// SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef CARVE_PRUNE_PRUNE_H_
#define CARVE_PRUNE_PRUNE_H_

#include <cstdint>
#include <filesystem>

#include "absl/status/statusor.h"
#include "carve/sidecar/carve.pb.h"

namespace carve::prune {

// Returns `records` with every row whose `written_at` is set AND older than
// `cutoff` (unix seconds) removed; rows with `written_at == 0` are always kept
// (an unstamped record is either pre-`written_at` or one whose scan did not fully
// resolve and is awaiting a re-scan, so it is not a GC candidate). Order and the
// `schema_version` are preserved. Pure: no filesystem access.
[[nodiscard]] ActionRecords PruneRecords(const ActionRecords& records, std::int64_t cutoff);

// Loads the sidecar at `path`, drops rows older than `cutoff` (see
// `PruneRecords`), writes it back atomically, and returns how many records were
// removed. A missing sidecar is not an error and removes nothing (returns 0).
// The compilation database is not rewritten here; it is regenerated by the next
// `refresh`.
[[nodiscard]] absl::StatusOr<int> RunPrune(const std::filesystem::path& path, std::int64_t cutoff);

}  // namespace carve::prune

#endif  // CARVE_PRUNE_PRUNE_H_
