#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
#
# Launcher generated by carve_refresh (rules/carve.bzl). Runs the carve binary
# over the configured targets and writes the compilation database to the
# workspace root. Invoke via `bazel run`, not `bazel build`.
set -euo pipefail

# --- runfiles.bash initialization (bazelbuild/bazel tools/bash/runfiles) ---
# shellcheck disable=SC1090,SC1091
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
  source "$0.runfiles/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
  {
    echo >&2 "ERROR: cannot find $f (runfiles.bash)"
    exit 1
  }
set -e
# --- end runfiles.bash initialization ---

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo >&2 "carve_refresh: use 'bazel run', not 'bazel build' (carve runs 'bazel aquery')."
  exit 1
fi

carve="$(rlocation "@@CARVE_RLOCATION@@")"
if [[ -z "${carve}" || ! -x "${carve}" ]]; then
  echo >&2 "carve_refresh: could not locate the carve binary in runfiles (@@CARVE_RLOCATION@@)."
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
exec "${carve}" refresh \
  --targets="@@TARGETS@@" \
  --output="@@OUTPUT@@" \
  --sidecar="@@SIDECAR@@" \
  --project_id="@@PROJECT_ID@@" \
  "$@"
