#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
#
# Launcher generated by carve_aspect_refresh (rules/carve.bzl). Merges the
# per-action shards that cc_carve_aspect built into the compilation database at
# the workspace root. Invoke via `bazel run`, not `bazel build`.
#
# Layer C split: the shards are produced by the outer build (one cacheable action
# per compile action, so an edit re-shards only what changed); this run step just
# aggregates them - it does NOT re-run aquery.
set -euo pipefail

# --- runfiles.bash initialization (bazelbuild/bazel tools/bash/runfiles) ---
# shellcheck disable=SC1090,SC1091
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
  source "$0.runfiles/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
  {
    echo >&2 "ERROR: cannot find $f (runfiles.bash)"
    exit 1
  }
set -e
# --- end runfiles.bash initialization ---

if [[ -z "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
  echo >&2 "carve_aspect_refresh: use 'bazel run', not 'bazel build'."
  exit 1
fi

carve="$(rlocation "@@CARVE_RLOCATION@@")"
if [[ -z "${carve}" || ! -x "${carve}" ]]; then
  echo >&2 "carve_aspect_refresh: could not locate the carve binary in runfiles (@@CARVE_RLOCATION@@)."
  exit 1
fi

manifest="$(rlocation "@@MANIFEST_RLOCATION@@")"
if [[ -z "${manifest}" || ! -r "${manifest}" ]]; then
  echo >&2 "carve_aspect_refresh: could not locate the shard manifest in runfiles (@@MANIFEST_RLOCATION@@)."
  exit 1
fi

# Resolve every shard's runfiles path into a comma-separated --sidecars list.
sidecars=""
while IFS= read -r key; do
  [[ -n "${key}" ]] || continue
  path="$(rlocation "${key}")"
  if [[ -n "${path}" && -r "${path}" ]]; then
    sidecars="${sidecars:+${sidecars},}${path}"
  else
    echo >&2 "carve_aspect_refresh: warning: shard not found in runfiles: ${key}"
  fi
done <"${manifest}"

if [[ -z "${sidecars}" ]]; then
  echo >&2 "carve_aspect_refresh: no shards to aggregate (did the aspect run over any cc targets?)."
  exit 1
fi

cd "${BUILD_WORKSPACE_DIRECTORY}"
# The shards' sources are execution-root-relative; resolve them against the real
# (persistent) execroot, which only `bazel info` outside the sandbox can give.
execroot="$(${BAZEL:-bazel} info execution_root)"
exec "${carve}" aggregate \
  --sidecars="${sidecars}" \
  --output="@@OUTPUT@@" \
  --directory="${execroot}" \
  --project_id="@@PROJECT_ID@@" \
  "$@"
